### PR TITLE
Add 'colette', timer freeze for groovin upper and VOLZZA 2

### PR DESCRIPTION
**Pull request by ikaros14**
I'm sorry for not careful and many commit

### CODE REVIEW

**Comment by mon** [comment]
You will have to fix the merge conflicts first, sorry... reflecbeat-groovin-upper.html looks like it was auto-formatted or something, is your editor doing it?

**Comment by ikaros14** [comment]
existing file looks like it was auto-formatted. I just added a support version date and timer freeze and modified the indentation.
I didn't have the permission to write, so I couldn't fix the conflict myself. It may be my problem not familiar with git. sorry.

**Comment by mon** [comment]
Hopefully I have time for this tonight - please keep in mind that having to fix your indentation and merge conflicts myself makes the process slow. In future, try to only make small changes.

**Comment by ikaros14** [comment]
Ok. To add PatchContainer, I downloaded it with Raw, modified it to Notepad++, and uploaded it again, but I had a problem with indentation, so I modified it again. I'll be careful from now on. sorry again

**Comment by mon** [comment]
Looking better now - if you're happy with my changes, I will merge

**Comment by ikaros14** [comment]
Cool. thanks for work!

**Pull request merged**
