### PR TITLE
Added Sinobuz Omnimix DLL Fix

### PR DESCRIPTION
**Pull request by JamesLewisLiu**
Everything Works Except Free play text to LED ticker (Upper left)
Which I have compared to Orig and didn't work and IDK what should i do to get it work

### CODE REVIEW

**Comment by mon** [comment]
LGTM, I'll check LED ticker later.

To merge this though, I need to make a decision:
Add it to the full patch list, which requires a thumbnail image for the main page
Add it as a separate section to the main sino page (like what Jubeat does)

What do you think?

**Comment by JamesLewisLiu** [comment]
I think the second one is best , since it will make the index neat.

**Comment by mon** [comment]
Alright - it needs a slight code change (for DLL descriptions) I'll do it on boxing day I think

**Comment by mon** [comment]
Added the required changes and edited your branch, however:

`"Level 12 Unlocked" is neither on nor off!`

Could you fix or remove it?

**Comment by JamesLewisLiu** [comment]
Just remove it ,since the omni one has been done the LV12 fix.
But the Strange thing is I never happened this problem,but when I use my roommate's computer this problem came out

**Comment by mon** [comment]
You don't even need the WAMP server - there shouldn't be any CORS issues, so just open the html in your browser of choice

**Pull request merged**
