### PR TITLE
Change to select the version after selecting the game

### PR DESCRIPTION
**Pull request by ikaros14**
index.html used the logo for the first version

### CODE REVIEW

**Comment by mon** [comment]
Ah, sorry - I was thinking of keeping a single index.html and using CSS to expand the sections

**Comment by ikaros14** [comment]
oh it's ok. I was hasty.

**Comment by mon** [comment]
Btw, I finally implemented the CSS version - take a look at index.html and tell me what you think :)

**Comment by ikaros14** [comment]
I don't know about anything else I think it's cool to use a cab image. thanks!

**Comment by ikaros14** [comment]
https://github.com/ikaros14/BemaniPatcher/commit/8a041f557bbb04ec4792a4176093dd3ff538c557

How about this style?

**Pull request closed without merging**
