### PR TITLE
Synchronica

### PR DESCRIPTION
**Pull request by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora**

### CODE REVIEW

**Comment by mon** [comment]
Nice! Just need to resize the image to 128x128px and it's good for merge!

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
credit to Yonokid#9492 for share with everyone :)

**Comment by Yonokid** [comment]
bro those aren't my patches how did you get them

**Comment by kyoubate-haruka** [comment]
> 
> 
> Thank you Yonokid#9492.

Given the fact I've only ever linked FGO (whose patches are for development help only in the first place, since they wouldn't help you getting the game running) under my account, I find it quite funny how you'd think it's him doing the patches. I mean not that I particularly care, but if any of this would be already useful for the end-user, you know I could have just uploaded it to the public bemanipatcher myself? lol

Also by the way @mon, it doesn't even work because he didn't realize I edited the path of the jQuery JS to be local, which doesn't exist on your webserver (I prefer to locally host everything), which makes it even funnier, like he didn't even test it.

**Comment by mon** [comment]
In that case I've reverted this too

**Pull request merged**
