### PR TITLE
SDVX6, IIDX28

### PR DESCRIPTION
**Pull request by drmext**

### CODE REVIEW

**Comment by mon** [comment]
Autoplay PRs are not accepted due to the ease of accidental bans from unaware users.

Also, fix your indentation for the bistrover patch.

Please re-open your PR once you have fixed these issues! The rest looks good.

**Comment by drmext** [comment]
Someone else can pattern match when the time is right

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
None server (Enigma, Arcana, Programmed Life) allows SDVX6 and IIDX28.

**Comment by mon** [comment]
But they will, when those games become n-1

**Pull request closed without merging**
