### PR TITLE
Add English folder text, Add 2018-10-23 support.

### PR DESCRIPTION
**Pull request by camprevail**

### CODE REVIEW

**Comment by mon** [comment]
Indentation is messed up, please use spaces. Otherwise looks good

**Comment by camprevail** [comment]
Updated!

**Comment by mon** [comment]
First indent level is still a tabstop

**Comment by camprevail** [comment]
Damn lol ok hang on

**Comment by camprevail** [comment]
Should be set now >.<

**Comment by mon** [comment]
lul

line 15, 35, 49, 69, 79, 84, 121

**Comment by camprevail** [comment]
fingers crossed

**Pull request merged**
