### PR TITLE
Chuni: Better patch for head-to-head play

### PR DESCRIPTION
**Pull request by lin714093880**
Regarding the previous PR (#128), @esterTion came up with a better solution. It seems like just turning off the asynchronous flag for the connection fix the problem completely.

Maybe the CHUNITHM engineers simply forgot that the connection is created asynchronously and instead programmed everything in sync mode..

### CODE REVIEW

**Comment by mon** [comment]
Is it essential to disable the old patch? It's less "clean" that way

**Comment by lin714093880** [comment]
The old patch would be adding unnecessary lag on connection but probably won’t affect actual gameplay. I just wanted to give an option for people using the old patch to remove it.

I can get rid of the option if you think it’s unnecessary.

**Comment by mon** [comment]
Did you close the PR by accident?

And yeah, a small connection lag should be fine vs a "don't enable this patch" request.

That being said, this situation happens a lot - it might be worth me integrating a "always set these bytes" feature to accommodate updated patch sets. Thoughts?

**Comment by lin714093880** [comment]
Yeah, accidentally clicked Close and comment. Didn't mean to close it.

I'll remove the option for now then.

**Pull request merged**
