### PR TITLE
kaimei riddles final hex edits

### PR DESCRIPTION
**Pull request by Subject38**

### CODE REVIEW

**Comment by Subject38** [comment]
might want to fix icon. also might want to include a note that with most servers, a lot of these hex edits are super harmful lol

**Comment by wz18207** [comment]
i think it can be merged because kaimei riddles has become n-1 right now.

**Comment by mon** [comment]
> i think it can be merged because kaimei riddles has become n-1 right now.

I've been meaning to add a "danger" tooltip for hex edits that might break things, so I took this opportunity. Sorry for the delay.

**Comment by wz18207** [comment]
> > i think it can be merged because kaimei riddles has become n-1 right now.
> 
> I've been meaning to add a "danger" tooltip for hex edits that might break things, so I took this opportunity. Sorry for the delay.

nah its up to you. add 'danger' tag may help most people who doesnt read any tooltip when they patch their games.

**Pull request merged**
