### PR TITLE
Add jubeat festo

### PR DESCRIPTION
**Pull request by camprevail**
Cause it's been out for well over a year now so why not.

### CODE REVIEW

**Comment by mon** [comment]
Icon isn't centered, fix that and we're golden!

**Comment by camprevail** [comment]
Uhhhh.... you sure? Looks pretty centered to me... If we're going by the "e" in "jubeat"

**Comment by mon** [comment]
I'm going off the little circular lines on the right side making things off

**Comment by camprevail** [comment]
Ah okay. Fixed :)

**Pull request merged**
