### PR TITLE
Patcher changes, IIDX SIRIUS thing

### PR DESCRIPTION
**Pull request by Poliwrath**
Added option for EXE games, includes IIDX SIRIUS as a example (classes and other stuff still have the DllPatcher name)

Slight changes to how errors / force loading works

### CODE REVIEW

**Comment by mon** [comment]
I think it's best to just accept _any_ filetype and not worry about exe/dll, since surely there are other files that can be patched as well. For example, I can think of some XML find/replace ops that I might add for music db unlocks.

I can make those changes sometime over the next few days if you want, or modify the PR for it.

**Comment by Poliwrath** [comment]
Alrighty, should I close this PR until you've done the changes?

**Comment by mon** [comment]
Keep it open so I remember

**Comment by mon** [comment]
Wow this took a while hey, exe support has landed now. Feel free to reopen fresh or do a big rebase or something.

**Pull request closed without merging**
