### PR TITLE
add sdvx eg support

### PR DESCRIPTION
**Pull request by wz18207**
i have to admit that staying sane is a willpower drain.

### CODE REVIEW

**Comment by Y2K-x** [comment]
Just beat me to the punch, I had my PR all set up, and I check back and you had already submitted it! Darn! :P

In any case, I would suggest crediting where you had gotten the patches from, seems to me like you had pulled them from elpis.fun, comparing the two. Just good edicate.

**Comment by mon** [comment]
While we wait for a reply to Y2K's query, did you know there is also a "integer text entry" option for patches? It might make the FPS patch cleaner, but it might also just be too difficult...

**Comment by wz18207** [comment]
Well, to be honest, the frame rate patch is quoted from my friend, I am not very clear about the specifics.  I can revoke this commit if I allow it, I don't like the game itself

**Comment by drmext** [comment]
elpis.fun just ran this https://github.com/drmext/BemaniPatcher/blob/c4d42b57b70c9e8eaf2f455cad9fb8fc265c29a2/docs/sdvx.py

**Pull request closed without merging**
