### PR TITLE
add patches for jubeat festo

### PR DESCRIPTION
**Pull request by ikaros14**
I organized all the markers and backgrounds(name from official website). If it's a problem because there are too many markers, please modify them freely. (I think it's better to add a dropdown to css)

### CODE REVIEW

**Comment by ikaros14** [comment]
and... Umaru-chan background image is missing in festo omnimix. I know this isn't the right place to report, but I don't have your another contact. 😅

**Comment by mon** [comment]
RE: markers etc. Please ensure you have the latest omnimix data. 3.1 added the removed marker and background textures, it must be installed!

I'll check this tomorrow, it's a bit late... I almost think it would be cool to have a "union type" - radio, dropdown, or image list (to preview markers)

**Comment by ikaros14** [comment]
Yeah, I use additional data in 3.1.0, other markers and backgrounds are fine. but only the umaru-chan background is problematic.

It'd be great to include the preview image, but I think it'll be a lot of work lol

Good night

**Comment by mon** [comment]
I will have to come back to this later (for dropdown/images etc). For now, I'll just merge with the radio boxes.

**Pull request merged**
