### PR TITLE
iidx 2021070500

### PR DESCRIPTION
**Pull request by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora**
This is removed in the original. {
                        name: "DJ. AUTO",
                        patches: [{ offset: 0x48D069, off: [0x00], on: [0x01] }],
                    },

### CODE REVIEW

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
credit to TPG#7803 chuchy#3566 5555#5555 in 1cc

**Comment by mon** [comment]
Your continual PRs, misattributions of source (confirmed 3+ wrong attributions so far), and "sneaky" attempts to publicise autoplay patches in every single IIDX PR have led me to believe you are doing all of this in bad faith.

Come back when you've learnt some manners.

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
The source is correct, 1cc server.
It's not a sneaky. It's deleted in PullRequest.

**Comment by dannylin0711** [comment]
Then you shouldn't post it in comment either.

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
I don't want secrets from BemaniPatcher. If some one wishes to have DJ AUTO, he can have it.

**Comment by camprevail** [comment]
1cc IS bad faith. They don't follow the rules that the greater community adheres to. I suggest you leave their server. You need to understand these rules, because all you're doing is making yourself look like an ass.

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
Where is rules?

**Comment by camprevail** [comment]
They're pretty simple, but you won't learn them from being in 1cc. 
- Don't mess with data newer than 6 months. If you do, keep it to yourself, and absolutely don't upload public hex edits!
- Don't upload autoplay patches
- Don't do anything to piss off your private eamuse server provider. Such as playing unsupported data.
- Don't be a dick.
It's pretty much all common sense so we don't get sued by konami again.

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
Sorry! I did not create it. I am republishing it from 1cc server.
I don't use a service provider.
The patch file is distributed in 1cc, I want to share it to members outside in 1cc.
DJ Auto can be for practice. I don't use him.

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
In 1cc, members are hostile to distribution of the patches.

**Comment by camprevail** [comment]
If they are "hostile to the distribution of the patch file" then it sounds like you do not have permission to share these edits!

**Comment by dannylin0711** [comment]
> 
> 
> Sorry! I did not create it. I am republishing it from 1cc server.
> I don't use a service provider.
> The patch file is distributed in 1cc, I want to share it to members outside in 1cc.
> DJ Auto can be for practice. I don't use him.

No, that's not an excuse. It's wrong when you get this idea.

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
No, it's a public file.
1cc is hostile towards distribution of "private" patch files. However, it's unfair to keep it in secret.

**Comment by dannylin0711** [comment]
You didn't look what camprevail said

>     * Don't mess with data newer than 6 months. If you do, keep it to yourself, and absolutely don't upload public hex edits!

**Comment by camprevail** [comment]
You just need to stop uploading anything here that comes from 1cc. Please. It's only causing drama.

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
It's created by other members.
Why is it a drama? It's patch files for public usage.

**Comment by dannylin0711** [comment]
No, this data should not be public at all. Don't you understand?

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
It's not my responsibility. The game file is distributed in 1cc by chuchy#3566.

**Comment by dannylin0711** [comment]
No, posting the patch here IS your responsibility. Don't try to shrink responsibility to 1cc or any others.

**Comment by CK-Tex** [comment]
He is obviously playing dumb.

**Comment by camprevail** [comment]
It's not your job, you didn't create the patches, and you don't have permission. I don't know how you don't see the issue with any of that.

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
It's distributed in public 1cc. Any one can enter 1cc and he will see the patch file. I am uploading it here for people outside of 1cc.

**Comment by Subject38** [comment]
even 1cc knew to remove the auto play edits once they realized their mistake. you just put it in the comment for no good reason

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
It's unfair to keep it in secret.

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
I do not understand why DJ Auto is deleted.
MAX play in Youtube is okay.

**Comment by dannylin0711** [comment]
You said 1cc is public, then said it's private. Your words are inconsistent.

**Comment by dannylin0711** [comment]
> 
> 
> I do not understand why DJ Auto is deleted.
> MAX play in Youtube is okay.

Because that's what idiots do, posting something forbidden.

**Comment by Subject38** [comment]
data videos on YouTube are never ok. dj auto should be kept private because a lot of players go to bemanipatcher just to grab the edits for their game and seeing dj auto is not great for random players because it gives them the option to submit fraudulent scores to unofficial networks with very little work

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
1cc is a public. However, the patch file is not in open internet.
Why is MAX play forbidden? https://www.youtube.com/watch?v=u9R1hIj_Gq8
If a member is banned from his unofficial service provider, it's the fault of the member.

**Comment by Subject38** [comment]
that's not what I meant. an auto play video is very different from a player achieving MAX- what are you on about?

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
https://www.youtube.com/watch?v=2qIWo1KUpi4

**Comment by Subject38** [comment]
"CS" not data LOL ????

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
What?

**Comment by Subject38** [comment]
that was a console style auto play video those are obviously fine. arcade data auto play videos are not at all the same and very much not fine

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
It's a open download. Any one can share any video to Youtube.

**Comment by Yonokid** [comment]
auto play patches aren't shared so people don't use them to cheat. most people consider that obvious

**Pull request closed without merging**
