### PR TITLE
SDVX II patches

### PR DESCRIPTION
**Pull request by Yonokid**
unfortunately these were the only two patches I was able to create but I was mostly aiming for a working timer freeze. Note that this only works with the phaseii dll, the sows dll seems to be extremely messed up. I can create new offsets for it, but since its the same datecode, how would I list it within the html?

### CODE REVIEW

**Comment by mon** [comment]
Is the sows dll different enough that the patches you've made get rejected for being a different DLL? Or are the offsets all fine looking but the patches just don't work? Cause if that's the case, the datecode can just have (phaseii) and (sows) next to it and it will select the right one.
If the bytes are the same, then I might have to introduce a new pseudo-patch that just checks for some bytes in a certain spot.

This PR has a few other issues but I can fix them myself before merge so don't worry
- image needs to be 128px (honestly I'm thinking of upgrading them all the 256px soon, the low res is kinda annoying me)
- the cloudflare-injected js script doesn't need to be there

**Comment by camprevail** [comment]
They appear to be two completely different DLLs, indicating they are not from the same update. The sows one also has coin data stripped of course.

**Comment by mon** [comment]
Tell me what you think of my changes

**Comment by Yonokid** [comment]
looks great, thank you

**Pull request merged**
