### PR TITLE
Update museca2.html

### PR DESCRIPTION
**Pull request by camprevail**

### CODE REVIEW

**Comment by mon** [comment]
Thoughts on just deleting in instead of "disable this"?

**Comment by camprevail** [comment]
If we delete it, people won't be able to disable it to switch to the other mod
    On Sunday, August 25, 2019, 07:40:50 PM EDT, Will <notifications@github.com> wrote:  
 
 
Thoughts on just deleting in instead of "disable this"?

**Comment by camprevail** [comment]
*If we delete it, people won't be able to disable it to switch to the other mod
One prevents the other from working

**Comment by Akubits** [comment]
It just occurred to me that it's good practice to backup your dlls every time you edit them, but i see the point in keeping it for people who really didn't. Also, this might just be me being nitpicky but what's up with the "play 3 songs" tool tip? You don't need to play 3 songs to activate it as what it does is just prevents the game from going to the "game over" screen after showing the results of the third song. I'm not really asking to remove it, just curious.

**Comment by camprevail** [comment]
I was expecting it to work like pfree on voltex at first, where it immediately jumps to the 3rd song. I thought it wasn't working at first but then I realized it was when I finished my 3rd song. 
 
  On Mon, Aug 26, 2019 at 10:59 AM, Akubits<notifications@github.com> wrote:   
It just occurred to me that it's good practice to backup your dlls every time you edit them, but i see the point in keeping it for people who really didn't. Also, this might just be me being nitpicky but what's up with the "play 3 songs" tool tip? You don't need to play 3 songs to activate it as what it does is just prevents the game from going to the "game over" screen after showing the results of the third song. I'm not really asking to remove it, just curious.

**Comment by Akubits** [comment]
Oh wait is that what you were expecting it to do? I don't use pfreepanic so I didn't know that that was how it was supposed to work. Thanks for clearing that up!

Additionally, finding another edit that makes it work the way you expected is probably easy to implement now that I know how the game does it.

**Comment by camprevail** [comment]
Nah pfree panic just uses my infinite 1st song hex.  
 
  On Mon, Aug 26, 2019 at 11:51 AM, Akubits<notifications@github.com> wrote:   
Oh wait is that what you were expecting it to do? I don't use pfreepanic so I didn't know that that was how it was supposed to work. Thanks for clearing that up!

Additionally, finding another edit that makes it work the way you expected is probably easy to implement now that I know how the game does it.

**Pull request merged**
