### PR TITLE
Create Bistrover

### PR DESCRIPTION
**Pull request by 6745**
edits for latest bist

### CODE REVIEW

**Comment by shellqiqi** [comment]
I suppose that some changes need to be done.
- Rename ./Bistrover to ./bistrover.html
- Add a entry in index.html

**Comment by mon** [comment]
I will not accept this pull request unless
- filenames are all lowercase
- game image is included at the correct resolution

**Comment by mon** [comment]
All images in the repository are 128x128px PNGs, you uploaded a 400x400px JPG. Please correct.

**Comment by 6745** [comment]
ah shoot 1 sec reuploaded wrong one

**Comment by mon** [comment]
What did you resize this image with, a cheese grater? Get some bicubic in your life. I'll merge as-is and fix it myself.

**Pull request merged**
