### PR TITLE
Use a cleaner pop'n music peace image

### PR DESCRIPTION
**Pull request by mbilker**
The current image for pop'n peace is a little blurry. I found the source image via a quick search and resized the image with `convert peace.jpg -resize 128x128 peace.png`.

### CODE REVIEW

**Comment by mbilker** [comment]
Also, the new image is smaller without resorting to image minification tricks.

**Comment by Poliwrath** [comment]
https://p.eagate.573.jp/game/kac/kac8th/top/?___REDIRECT=0 is the source for most icons for new games btw, just resized with paint.NET to 128x128 (I think I used the ""Best Quality"" option, but I guess that's not really the best)

**Comment by mbilker** [comment]
@Poliwrath I actually used https://eam.573.jp/app/web/img/popn_peace_l.jpg which is 220x220.

**Comment by Poliwrath** [comment]
Thanks for the link

**Pull request merged**
