### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by Tomo-Tg**
Addition of games that are no longer n-0 and games that are more than 1 year old, as well as updates to existing patches.
I found some errors and re-pulled the pull request again.
My apologies for the inconvenience.

### CODE REVIEW

**Comment by mon** [comment]
It's no problem, thanks for the contribution.
I still need a day to find time to inspect properly, but some initial thoughts from a quick look

- Diif looks nice and clean for IIDX changes
- Games with only 1 entry (EG: dancerush) don't need a folder. I can fix this, you don't have to.
- I'm not sure about including Kancolle. It's not rhythm, and it's not konami. I also don't have Initial D patches for this reason. But due to the "no n-0" rule, patches are a lot less frequent, so maybe I should rethink this rule.

**Comment by Tomo-Tg** [comment]
I forgot that there is a rule that only Konami or rhythm games are allowed...
For me, it is very convenient to be able to patch different games on one site.
I would be happy if you could improve this rule

**Comment by Tomo-Tg** [comment]
I collected and posted a collection of patches that I had saved on my pc.
The DRS patch was a patch that was posted on some arcade forum a long time ago
I didn't think that the patch contained false and I have not tested it, I will test all the patches now, so please wait a while
Sorry for the inconvenience.

**Comment by Tomo-Tg** [comment]
The only thing I was able to test was the Kancolle...
There was no problem with the test, but if you decide not to include the Kancolle , then my pull request was for nothing...
If I have the opportunity to make a pull request again, I will make sure to test it thoroughly before submitting it.
I apologize for taking so much of your time because of my terrible pull request

**Comment by Tomo-Tg** [comment]
So far, all of the patches we have tested have been fine.
All of the games listed in the patches showed signs of having been uploaded once, but only DRS showed no signs of data having been uploaded at all, and with a little digging, it was easy to tell that it was a fake.
I apologize for any inconvenience my mistake may have caused.

The only test left is the Beatmania
Patches that have been tested
Kancolle
pop'n music 26 解明リドルズ
Nostalgia Op.3
DDR A20 Plus

**Comment by Tomo-Tg** [comment]
With the help of a friend, we were able to complete the test and no problems were identified.
I have removed the DRS patch.
My commit submitted the 2020-11-16 version of the nostalgia op3 patch, but now it looks like the 2021-12-22 version of the nostalgia op3 patch has also been submitted, so I think we need to integrate the patches, should I create them?
If we do integrate, I will create an integrated patch and submit it to this commit.

**Comment by mon** [comment]
Thanks for your patience and thank you **very much** for the testing. I know it's a pain to do, and I really appreciate that you've spent the time.

I merged the other Op3 patches as they looked good, so yes, adjust yours to merge in the changes together.

I think I will adjust the submission rule to be "somewhat recent PC based arcade games" So kancolle, initial D, etc will be OK to submit. I will continue to tweak the rule if I get a lot of junk submissions for games outside of rhythm games.

**Comment by Tomo-Tg** [comment]
Are you able to commit without problems?
Thank you for allowing initial D,kancolle , etc.
I will make a pull request for the A patch in the next few days.

**Comment by Tomo-Tg** [comment]
Added support for Initial D

**Comment by mon** [comment]
The review comments I left have yet to be resolved, please take a look at them.

Where'd the patch set come from? It seems quite comprehensive, especially the extra notes in the html.

**Comment by mon** [comment]
Also, there are merge conflicts that would need resolution

**Comment by Tomo-Tg** [comment]
I'm not familiar with Github and don't know where to find review comments, if you don't mind, could you please comment here?
The idz patch was released on Emuline. It has been tested and I have committed it with my addition of tooltip.

**Comment by mon** [comment]
If you scroll up a little you can see "mon started a review" and the 2 comments I left on some of the files. They are marked with yellow "Pending" labels.

IDZ patch is OK then, thanks.

**Comment by Tomo-Tg** [comment]
I couldn't find the review no matter how many times I looked for it, so I did some research and found the information that reviews with the Pending label are not visible to others. Could you please make them visible to me?

**Comment by mon** [comment]
> I couldn't find the review no matter how many times I looked for it, so I did some research and found the information that reviews with the Pending label are not visible to others. Could you please make them visible to me?

Oh my goodness, I am so sorry. I never even realised that was possible. Have made them un-pending.

**Comment by Tomo-Tg** [comment]
Fixed, is this a problem?

**Pull request merged**
