### PR TITLE
Fategrandorder

### PR DESCRIPTION
**Pull request by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora**

### CODE REVIEW

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
The original is https://gmg.hopto.org:82/gmg/bemanipatcher/

**Comment by Yonokid** [comment]
how did you get this

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
Haruka

**Comment by Yonokid** [comment]
did they send it to you?

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
Yes, 1cc.

**Comment by Yonokid** [comment]
why?

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
Are you Mitsuhide#6002?

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
Why is it closed?

**Comment by mon** [comment]
Not a rhythm game. If I start accepting patches for every arcade game in existence, my head will explode.

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
https://github.com/mon/BemaniPatcher/pull/211
https://github.com/mon/BemaniPatcher/pull/167

**Comment by mon** [comment]
IDZ was deleted due to this new rule. Bombergirl PC is the only exception because it's still a weeb konami property (this repo is *Bemani*patcher after all).

**Comment by ora-ora-ora-ora-ora-ora-ora-ora-ora-ora** [comment]
Sorry!

**Pull request closed without merging**
