### PR TITLE
Chunithm and other big patches

### PR DESCRIPTION
**Pull request by Yonokid**
Changelog:
Chunithm "Plus" versions have been separated into their own pages to keep formatting the same; all versions have new images
Chunithm Sun and Sun Plus have been added
Jubeat Ave has been added
Old dancerush patches have been appended
Taiko's name has been slightly modified to reflect changes
Wacca Reverse has been added

### CODE REVIEW

**Comment by mon** [comment]
I cannot merge this with the changes to the images - most of them increased in size, with 0 visible change to the actual image (and 0 change to the actual dimensions, either).

I'll review the rest later

**Comment by Yonokid** [comment]
yeah sorry that it changed all of the images; I ran an imagemagick command in bulk assuming it would only modify ones that weren't 128x128 but it seemed to have made minor changes to all of them

**Comment by mon** [comment]
> yeah sorry that it changed all of the images; I ran an imagemagick command in bulk assuming it would only modify ones that weren't 128x128 but it seemed to have made minor changes to all of them

Just to be clear I'm expecting a commit to fix this before I look at the rest

**Comment by Yonokid** [comment]
nevermind, too many people have said they don't like the images regardless so im closing this request until I make better ones

**Comment by mon** [comment]
Damn seriously? And I literally just finished looking at the rest 😅

Well at any rate, once you satisfy people regarding the images, use spaces instead of tabs for indentation, it's screwy
image

The real solution here is for me to add auto-formatting as part of the PRs, but last time I checked github makes that really hard (API key permissions or something)

**Comment by Yonokid** [comment]
ah the curse of using notepad++ as an ide lol. I'll look through my files again then to make sure it shows up normally

**Comment by Yonokid** [comment]
ok now I am satisfied with my changes:
html files and images now have the same name and are categorized with their associated game
images are (generally speaking) standardized now
the site will switch to a dark theme if the user's browser/system preference is set to dark
deprecated patches have been marked with the danger tooltip
all tab indents have been changed to spaces
ported your "skip update check" patch from amazon to amazon plus
datecode versions have been added to games that had none
i do not remember the rest

**Comment by mon** [comment]
I like the auto-darkmode, that's well overdue.

I *cannot* rename all the .html files as that breaks every single backlink on the internet (of which there are _many_ to bemanipatcher). I would personally prefer games/<series>/<version>.html, but haven't bothered to fill in my local .htaccess file with 302s to solve the link rot.

Similarly with images, it might be worth folder-ising them, but I'm not gonna push for it (the change you've made already is great).

**Comment by mon** [comment]
If you do bother to put the images into folders, also make games with more than 10 mixes 2 digits - lexical sort strikes again
image

**Comment by Yonokid** [comment]
ok give me a couple minutes to revert the name changes on the html files

**Comment by Yonokid** [comment]
ok everything should be good now; ive also added the paradise lost image to chuni when the mouse hovers over the paradise image

**Comment by mon** [comment]
Some of these images are a bit screwy - why no more transparency? Why the huge decrease in sharpness?
image

**Comment by Yonokid** [comment]
Not really sure what happened with the sharpness? I recreated those images from source so I exported them as 128x128 images. The reason I removed transparency is because there were only about 3 images that had it; when put altogether its really an all or nothing situation, it looks strange when only a handful have transparency and all of the others have a white background. Transparent background images are also much harder to see in the newly added dark mode

**Comment by Yonokid** [comment]
Ok, I've pushed your changes. There's only two files that I'm very unwilling to change:
1. chuninewplus.html -> chusannewplus.html (having SDHD versions labeled as chusan makes them much easier to find)
2. resort_anthem.html -> resortanthem.html (this is the only file that used snake case and it was bothering me)

**Comment by mon** [comment]
Alright, I've added a `.htaccess` file. This PR is already huge, so if you want to utilise this to re-commit the cleaned up names, please make a new PR for it.

**Comment by Yonokid** [comment]
great thank you so much!!!!!

**Pull request merged**
