### PR TITLE
ROOTAGE->Rootage

### PR DESCRIPTION
**Pull request by Poliwrath**

### CODE REVIEW

**Comment by camprevail** [comment]
Uh oh Rootage is back on the patcher, everybody lose their shit and point fingers

**Comment by mon** [comment]
Plife has a large, leaky audience. It shouldn't be surprising that when they drop n-0, patches come out of the woodwork.

**Comment by Poliwrath** [comment]
Would it be OK to re-commit the patches that were up previously, or should I ask the author first?

**Comment by mon** [comment]
I will accept the PR to continue my current stance, but it's probably good faith to ask.

**Pull request merged**
