### PR TITLE
Add 2021051802

### PR DESCRIPTION
**Pull request by ikaros14**

### CODE REVIEW

**Comment by camprevail** [comment]
Can you not

**Comment by ikaros14** [comment]
> Can you not

what mean?

**Comment by mon** [comment]
*sigh* there is no way this is going to end well for anyone.

**Comment by camprevail** [comment]
> > Can you not
> 
> what mean?

I mean stop making patches for 1 week old data, which therefore promotes the use of said data.

**Comment by ikaros14** [comment]
https://github.com/mon/BemaniPatcher/blob/master/README.md

**Comment by ikaros14** [comment]
I'm one of the people who's worried about the latest build being leaked, but it's already happened. I know what you mean by that, but it's better to tell the person who leaked the data.

**Pull request merged**
